version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    container_name: power_server_db
    user: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/ -schemas=public -user=postgres -password=postgres -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      db:
        condition: service_healthy
  power:
    container_name: power_server
    build: .
    depends_on:
      flyway:
        condition: service_completed_successfully # wait for flyway to finish
    ports:
      - "8080:8080"
    environment:
      #DB
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    links:
      - db
volumes:
  db:
    driver: local